# Server port
server.port=${PORT:8080}

# MySQL Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false

# HR credentials
HR_USERNAME=${HR_USERNAME}
HR_PASSWORD=${HR_PASSWORD}
